# -*- coding: utf-8 -*-
"""Photovoltaic -Power-Generation-Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeFkEkvote3beoI5zLsRUwkd5q6Oe0p5
"""

# Commented out IPython magic to ensure Python compatibility.
# Clone the Stanford solar forecasting dataset repo
!git clone https://github.com/yuhao-nie/Stanford-solar-forecasting-dataset.git

# Move into the directory
# %cd Stanford-solar-forecasting-dataset

!ls

from google.colab import files
uploaded = files.upload()

import numpy as np

import pandas as pd
from google.colab import files

# Load the file
data = np.load('times_test.npy', allow_pickle=True)

# Check the basic structure
print("Type:", type(data))
print("Shape:", data.shape)
print("Data type inside array:", data.dtype)

# View the first few entries
print("\nFirst 5 entries:")
for i in range(min(5, len(data))):
    print(f"{i}: {data[i]} (type: {type(data[i])})")


# Load the datetime array
data = np.load('times_test.npy', allow_pickle=True)

# Convert to DataFrame of ISO timestamp strings
df = pd.DataFrame({'timestamp': [dt.strftime('%Y-%m-%d %H:%M:%S') for dt in data]})

# Save to CSV
csv_filename = 'times_test_converted.csv'
df.to_csv(csv_filename, index=False)
print(f"✅ Saved CSV as: {csv_filename}")

# Download the CSV
files.download(csv_filename)